cluster:
  mkdir -p logs/`date +"%Y-%m-%d"` &&
  sbatch
    --partition={resources.partition}
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --job-name=smk-{rule}-{wildcards}
    --output=logs/`date +"%Y-%m-%d"`/{rule}-`date +"%Y-%m-%d-%H%M%S"`.out
    --mail-type=ALL
default-resources:
  - partition=trc
  - mem_mb=1000
restart-times: 1
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 16
latency-wait: 60
jobs: 1
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: false