__default__:
    partition: trc # the partition you use
    mail-type: ALL # Get emails when a job is started and finished
    job-name: {rule}-{wildcards} # Name each job according to rule and the wildcards